run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - deadcode
    - gosec
    - goconst
    - revive

issues:
  exclude-rules:
    - path: ".*_test\\.go"
      linters:
        - errcheck